//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 06:46:52 PM MSK 
//


package org.onepf.repository.api.responsewriter.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for purchasesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="purchasesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="purchase" type="{}purchaseType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "purchasesType", propOrder = {
    "purchase"
})
public class PurchaseListEntity extends BaseListEntity{

    protected List<PurchaseEntity> purchase;

    /**
     * Gets the value of the purchase property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the purchase property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPurchase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PurchaseEntity }
     * 
     * 
     */
    public List<PurchaseEntity> getPurchase() {
        if (purchase == null) {
            purchase = new ArrayList<PurchaseEntity>();
        }
        return this.purchase;
    }


    @Override
    public JAXBElement<PurchaseListEntity> getAsJaxbElement(QName qname) {
        return new JAXBElement<PurchaseListEntity>(qname, PurchaseListEntity.class, null, this);
    }
}
